services:
  postgres:
    image: postgres:16.0-alpine
    ports:
      - 5432:5432
    volumes:
      - scheduler-db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: scheduler

  app:
    build: .
    ports:
      - 8080:8080
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://postgres:secret@postgres:5432/scheduler


volumes:
  scheduler-db:
